#define CURRENT_VERSION L"0.0.0.12"
#define RESOURCE_FILE_VERSION 0,0,0,12
#define RAW_FILE_VERSION 0,0,0,12
#define RAW_PRODUCT_VERSION RAW_FILE_VERSION
#define RESOURCE_PRODUCT_VERSION RESOURCE_FILE_VERSION
#define RESOURCE_LEGAL_COPYRIGHT "Copyright (c)2020 Jeremy Collake"
#define RESOURCE_COMPANY_NAME "Bitsum LLC"
